export default {
  CANVAS_HEIGHT: 500,
  AVG_PERSON_HEIGHT: 70,
  AVG_STORY_HEIGHT: 85,
  PADDING_X: 10,
  DOOR_WIDTH: 35,
  BUILDING_PADDING: 10,
  BLOCK_MAX_WIDTH: 90,
  BLOCK_MIN_WIDTH: 110,
  BAY_THRESHOLD: 20
};
